name: XIATools
main: zishu.xiatools.XIATools
author: Z1SHU
version: 1.0.0
commands:
  Fly:
    description: "/Fly"
    permission: XIATools.Fly

  Feed:
    description: "/Feed"
    permission: XIATools.Feed

  SetHome:
    description: "/SetHome"

  Home:
    description: "/Home"

  Back:
    description: "/Back"

  tpr:
    aliases: rtp
    description: "/tpr"

  Help:
    description: "/Help"

  Heal:
    description: "/Heal"
    permission: XIATools.Heal